新增对openresty的支持

diff --git a/ngmp b/ngmp
--- a/ngmp
+++ b/ngmp
@@ -1,26 +1,57 @@
 #!/bin/bash
 clear
 echo "Welecome to NGMP!"
-echo "Select Nginx Version:"
-echo "1. 1.25.4"
-echo "2. 1.24.0"
-echo "3. 1.22.1"
-echo "4. 1.20.2"
-echo "5. 1.18.0"
-read -p "Enter your choice: " nginx_choice
-if [ $nginx_choice -eq 1 ]; then
-    nginx_version="1.25.4"
-elif [ $nginx_choice -eq 2 ]; then
-    nginx_version="1.24.0"
-elif [ $nginx_choice -eq 3 ]; then
-    nginx_version="1.22.1"
-elif [ $nginx_choice -eq 4 ]; then
-    nginx_version="1.20.2"
-elif [ $nginx_choice -eq 5 ]; then
-    nginx_version="1.18.0"
+echo "This script will help you install Nginx, MariaDB and PHP on your system."
+echo "Select HTTP Server Type:"
+echo "1. Nginx"
+echo "2. OpenResty"
+read -p "Enter your choice: " http_choice
+if [ $http_choice -eq 1 ]; then
+    http_server="nginx"
+elif [ $http_choice -eq 2 ]; then
+    http_server="openresty"
 else
     echo "Invalid choice"
     exit 1
+fi
+if [ $http_server = "nginx" ]; then
+    echo "Select Nginx Version:"
+    echo "1. 1.25.4"
+    echo "2. 1.24.0"
+    echo "3. 1.22.1"
+    echo "4. 1.20.2"
+    echo "5. 1.18.0"
+    read -p "Enter your choice: " nginx_choice
+    if [ $nginx_choice -eq 1 ]; then
+        nginx_version="1.25.4"
+    elif [ $nginx_choice -eq 2 ]; then
+        nginx_version="1.24.0"
+    elif [ $nginx_choice -eq 3 ]; then
+        nginx_version="1.22.1"
+    elif [ $nginx_choice -eq 4 ]; then
+        nginx_version="1.20.2"
+    elif [ $nginx_choice -eq 5 ]; then
+        nginx_version="1.18.0"
+    else
+    echo "Invalid choice"
+    exit 1
+    fi
+elif [ $http_server = "openresty"]; them
+    echo "Select OpenResty Version:"
+    echo "1. 1.25.3.1"
+    echo "2. 1.21.4.3"
+    echo "3. 1.19.9.1"
+    read -p "Enter your choice: " openresty_choice
+    if [ $openresty_choice -eq 1 ]; then
+        openresty_version="1.25.3.1"
+    elif [ $openresty_choice -eq 2 ]; then
+        openresty_version="1.21.4.3"
+    elif [ $openresty_choice -eq 3 ]; then
+        openresty_version="1.19.9.1"
+    else
+        echo "Invalid choice"
+        exit 1
+    fi
 fi
 echo "Select PHP Version:"
 echo "1. 8.3"
@@ -114,8 +145,11 @@ else
     echo "Invalid choice"
     exit 1
 fi
-echo "Installing Nginx, PHP, and MariaDB..."
-echo "Nginx Version: $nginx_version"
+if [ $http_server -eq "nginx" ]; then
+    echo "Nginx Version: $nginx_version"
+elif [ $http_server -eq "openresty" ]; then
+    echo "OpenResty Version: $openresty_version"
+fi
 echo "PHP Version: $php_version"
 echo "MariaDB Version: $mariadb_version"
 mkdir $HOME/ngmp-data
@@ -134,25 +168,47 @@ else
     echo "Unsupported OS"
     exit 1
 fi
-# Download Nginx
-echo "Downloading Nginx $nginx_version"
-wget --no-clobber https://nginx.org/download/nginx-$nginx_version.tar.gz
-tar -xvf nginx-$nginx_version.tar.gz
-# Build Nginx
-cd nginx-$nginx_version
-./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre  --with-openssl-opt="include=/usr/include/openssl" --with-openssl-opt="lib=/usr/lib" --with-openssl-opt='enable-tls1_3' --with-openssl-opt='enable-tls1_2' --user=www-data --group=www-data --with-ld-opt="-Wl,-rpath,/usr/local/php/lib/" --pid-path=/var/run/nginx.pid --with-cc-opt="-O0"
-if [ $jobs == "1" ]; then
-    make && make install
-elif [ $jobs == "2" ]; then
-    make -j2 && make install
-elif [ $jobs == "4" ]; then
-    make -j4 && make install
-elif [ $jobs == "6" ]; then
-    make -j6 && make install
-elif [ $jobs == "8" ]; then
-    make -j8 && make install
+if [ $http_server -eq "nginx" ]; then
+    # Download Nginx
+    echo "Downloading Nginx $nginx_version"
+    wget --no-clobber https://nginx.org/download/nginx-$nginx_version.tar.gz
+    tar -xvf nginx-$nginx_version.tar.gz
+    # Build Nginx
+    cd nginx-$nginx_version
+    ./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre  --with-openssl-opt="include=/usr/include/openssl" --with-openssl-opt="lib=/usr/lib" --with-openssl-opt='enable-tls1_3' --with-openssl-opt='enable-tls1_2' --user=www-data --group=www-data --with-ld-opt="-Wl,-rpath,/usr/local/php/lib/" --pid-path=/var/run/nginx.pid --with-cc-opt="-O0"
+    if [ $jobs == "1" ]; then
+        make && make install
+    elif [ $jobs == "2" ]; then
+        make -j2 && make install
+    elif [ $jobs == "4" ]; then
+        make -j4 && make install
+    elif [ $jobs == "6" ]; then
+        make -j6 && make install
+    elif [ $jobs == "8" ]; then
+        make -j8 && make install
+    fi
+    cd ..
+elif [ $http_server -eq "openresty" ]; then
+    # Download OpenResty
+    echo "Downloading OpenResty $openresty_version"
+    wget --no-clobber https://openresty.org/download/openresty-$openresty_version.tar.gz
+    tar -xvf openresty-$openresty_version.tar.gz
+    # Build OpenResty
+    cd openresty-$openresty_version
+    ./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre  --with-openssl-opt="include=/usr/include/openssl" --with-openssl-opt="lib=/usr/lib" --with-openssl-opt='enable-tls1_3' --with-openssl-opt='enable-tls1_2' --user=www-data --group=www-data --with-ld-opt="-Wl,-rpath,/usr/local/php/lib/" --pid-path=/var/run/nginx.pid --with-cc-opt="-O0" --with-luajit
+    if [ $jobs == "1" ]; then
+        make && make install
+    elif [ $jobs == "2" ]; then
+        make -j2 && make install
+    elif [ $jobs == "4" ]; then
+        make -j4 && make install
+    elif [ $jobs == "6" ]; then
+        make -j6 && make install
+    elif [ $jobs == "8" ]; then
+        make -j8 && make install
+    fi
+    cd ..
 fi
-cd ..
 # Download PHP and MariaDB
 echo "Downloading PHP $php_version"
 git clone https://gitee.com/mirrors/php.git -b PHP-$php_version
