新增多线程编译选项

diff --git a/ngmp b/ngmp
--- a/ngmp
+++ b/ngmp
@@ -86,6 +86,27 @@ if [ $mariadb_binary_choice == "Y" ] || [ $mariadb_binary_choice == "y" ]; then
 else
     mariadb_binary="false"
 fi
+echo "Using Multi-Jobs Compile?"
+echo "1. No"
+echo "2. 2 Jobs"
+echo "3. 4 Jobs"
+echo "4. 6 Jobs"
+echo "5. 8 Jobs"
+read -p "Enter your choice: " mariadb_jobs_choice
+if [ $mariadb_jobs_choice -eq 1 ]; then
+    mariadb_jobs="1"
+elif [ $mariadb_jobs_choice -eq 2 ]; then
+    mariadb_jobs="2"
+elif [ $mariadb_jobs_choice -eq 3 ]; then
+    mariadb_jobs="4"
+elif [ $mariadb_jobs_choice -eq 4 ]; then
+    mariadb_jobs="6"
+elif [ $mariadb_jobs_choice -eq 5 ]; then
+    mariadb_jobs="8"
+else
+    echo "Invalid choice"
+    exit 1
+fi
 echo "Installing Nginx, PHP, and MariaDB..."
 echo "Nginx Version: $nginx_version"
 echo "PHP Version: $php_version"
@@ -124,12 +145,32 @@ fi
 # Build Nginx
 cd nginx-$nginx_version
 ./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre  --with-openssl-opt="include=/usr/include/openssl" --with-openssl-opt="lib=/usr/lib" --with-openssl-opt='enable-tls1_3' --with-openssl-opt='enable-tls1_2' --user=www-data --group=www-data --with-ld-opt="-Wl,-rpath,/usr/local/php/lib/" --pid-path=/var/run/nginx.pid --with-cc-opt="-O0"
-make -j2 && make install
+if [ $mariadb_jobs == "1" ]; then
+    make && make install
+elif [ $mariadb_jobs == "2" ]; then
+    make -j2 && make install
+elif [ $mariadb_jobs == "4" ]; then
+    make -j4 && make install
+elif [ $mariadb_jobs == "6" ]; then
+    make -j6 && make install
+elif [ $mariadb_jobs == "8" ]; then
+    make -j8 && make install
+fi
 # Build PHP
 cd ../php
 ./buildconf
 ./configure --prefix=/usr/local/php --with-config-file-path=/usr/local/php/etc --with-openssl --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --enable-mbstring --with-mysqli --with-pdo-mysql --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-curl --enable-zip --enable-soap --enable-bcmath --enable-sockets --enable-pcntl --enable-mysqlnd --with-mysqli-sock=/var/ --with-pkg-config-path=/usr/bin/pkg-config
-make -j2 && make install
+if [ $mariadb_jobs == "1" ]; then
+    make && make install
+elif [ $mariadb_jobs == "2" ]; then
+    make -j2 && make install
+elif [ $mariadb_jobs == "4" ]; then
+    make -j4 && make install
+elif [ $mariadb_jobs == "6" ]; then
+    make -j6 && make install
+elif [ $mariadb_jobs == "8" ]; then
+    make -j8 && make install
+fi
 # Build MariaDB
 if [ "$mariadb_binary" == "true" ]; then
     mv mariadb-$mariadb_version-linux-systemd-x86_64/ /usr/local/mariadb/
@@ -152,7 +193,17 @@ else
     -DMYSQL_UNIX_ADDR=/var/run/mariadb/mariadb.sock \
     -DDEFAULT_CHARSET=utf8mb4 \
     -DDEFAULT_COLLATION=utf8mb4_general_ci
-    make -j2 && make install
+    if [ $mariadb_jobs == "1" ]; then
+        make && make install
+    elif [ $mariadb_jobs == "2" ]; then
+        make -j2 && make install
+    elif [ $mariadb_jobs == "4" ]; then
+        make -j4 && make install
+    elif [ $mariadb_jobs == "6" ]; then
+        make -j6 && make install
+    elif [ $mariadb_jobs == "8" ]; then
+        make -j8 && make install
+    fi
     sudo /usr/local/mariadb/scripts/mysql_install_db --user=mysql --basedir=/usr/local/mariadb --datadir=/usr/local/mariadb/data
     sudo cp /usr/local/mariadb/support-files/my-huge.cnf /etc/my.cnf
     sudo /usr/local/mariadb/bin/mysqld_safe --user=mysql &
